language: python
sudo: false

python:
  - "3.6"

before_install:
  # Make sure that things work even if the locale is set to C (which
  # effectively means ASCII). Some of the input rst files have unicode
  # characters and we need to deal with this gracefully.
  - |
    if [[ $LOCALE == C ]]; then
        export LC_CTYPE=C
        export LC_ALL=C
        export LANG=C
    fi

install:
  - pip install -r requirements.txt

script:
  - ./get-help-source.sh
  - make html
  - ./checklinks source/*.md 
  - touch build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: build/html/
